# Generated by Django 2.2.12 on 2021-01-18 10:34

from django.db import migrations, models
import weibo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeiBo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, verbose_name='用户ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=30, verbose_name='用户昵称')),
                ('avatar', models.ImageField(null=True, upload_to='avatar')),
                ('info', models.CharField(default='', max_length=150, verbose_name='个人简介')),
                ('sign', models.CharField(default=weibo.models.default_sign, max_length=50, verbose_name='标签')),
                ('gender', models.CharField(max_length=1, verbose_name='性别')),
                ('location', models.CharField(default='-', max_length=50, verbose_name='地区')),
                ('birthday', models.DateField(default='2000-01-01', verbose_name='生日')),
            ],
        ),
    ]
